version: "3.0"

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin@!
      - MYSQL_DATABASE=jwttokenservice
      - MYSQL_PASSWORD=adminadmin@!
    ports:
      - "3306:3306"
    networks:
      - login-mysql

  login-api:
    image: login-api
    container_name: login-api-container
    restart: always
    ports:
      - "8200:8200"
    networks:
      - login-mysql
    depends_on:
      - docker-mysql
    environment:
      - DATABASE_HOST=docker-mysql
      - SWAGGER_BASE_URL=psp.yumyapps.com
networks:
  login-mysql:
    driver: bridge