spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}/jwttokenservice #select your desired database name
    username: root # database username
    password: adminadmin@! # database password
    hikari:
      pool-name: 'jwt-proto'
      minimum-idle: 5
      maximum-pool-size: 200
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  graphql:
#    graphiql:
#      enabled: true
#    schema:
#      introspection:
#        enabled: true #if we want to see the field data type
#      printer:
#        enabled: true
  application:
    name: login-api
jwt:
  security:
    key: '^+$Guidelines89797987forAlphabetical'

server:
  port: 8200
  error:
    path: /error